# Setup
title:               J. Chipman Codes
tagline:             'Returning to my roots'
description:         'A blog/portfolio where I talk about getting back into the dev game.'
url:                 https://jchipmancodes.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              James Chipman
#  url:               https://twitter.com/mdo
  email:             james.chipman@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
#version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
